### PR TITLE
Fix: WMOManager refactor

### LINKED ISSUE #116: Some WMO doodads render incorrectly (possibly load twice)
As caught by @timkurvers, it appears some WMO doodads render incorrectly. In fact, it would appear (based on observation) that some WMO doodads may be loaded and placed twice.

An example is the piston doodad in Tinkertown (in Ironforge). As it animates, there's visible z-fighting. Additionally, as it loads, there's a brief period where it's possible to see just a single instance of the doodad, before a second instance then appears.

screen shot 2016-02-10 at 6 16 36 pm

### PR DESCRIPTION
**Pull request by fallenoak**
* Fixed issue that resulted in duplicate WMO doodads appearing. (fixes #116)

* Added doodad reference tracking to WMOManager.

* Migrated all management logic out of WMO and WMOGroup classes.

* Added ContentQueue class to assist in loading content on behalf of map managers.

* Added WMOHandler class to assist in loading and unloading WMOs and WMOGroups from within WMOManager.

### CODE REVIEW

File: src/lib/game/world/content-queue.js [hunk 1]
```diff
@@ -0,0 +1,83 @@
+class ContentQueue {
+
+  constructor(processor, interval = 1, workFactor = 1, minWork = 1) {
```
Comment (timkurvers) [inline src/lib/game/world/content-queue.js]: The `interval` for `setTimeout` defaulting to 1 millisecond, is that intentional?

**Comment by timkurvers** [comment]
Really liking the idea of that `ContentQueue`! :+1:

File: src/lib/game/world/content-queue.js [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+      if (count > max) {
+        break;
+      }
+    }
+
+    this.schedule();
+  }
+
+  clear() {
+    this.queue = new Map();
```
Comment (timkurvers) [inline src/lib/game/world/content-queue.js]: We could use `queue.clear()` here (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear)

File: src/lib/game/world/content-queue.js [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+    let count = 0;
+
+    if (keyPattern.toString().includes('*')) {
+      for (const entry of this.queue) {
+        const key = entry[0];
+
+        if (key.startsWith(keyPattern.split('*')[0])) {
+          this.queue.delete(key);
+          count++;
+        }
```
Comment (timkurvers) [inline src/lib/game/world/content-queue.js]: I like the idea of having pattern support, but this strikes me as potentially confusing if I were to use `*-8` and it won't match anything. Is it supposed to support arbitrary patterns?

File: src/lib/game/world/wmo-manager/wmo-handler.js [hunk 4]
```diff
@@ -0,0 +1,398 @@
+import ContentQueue from '../content-queue';
+import WMOBlueprint from '../../../pipeline/wmo/blueprint';
+import WMOGroupBlueprint from '../../../pipeline/wmo/group/blueprint';
+import M2Blueprint from '../../../pipeline/m2/blueprint';
+
+class WMOHandler {
+
+  static LOAD_GROUP_INTERVAL = 2;
```
Comment (timkurvers) [inline src/lib/game/world/wmo-manager/wmo-handler.js]: Same question here with regards to 2 ms as a load interval.

File: src/lib/game/world/content-queue.js (hunk 3 above)
Comment (fallenoak) [inline src/lib/game/world/content-queue.js]: It's definitely incomplete. Maybe regexes would be a better fit?

I'd be okay junking this for now-- it's a hold over from a previous attempt I made at the refactor. I don't think I'm actually using pattern matching anywhere anymore.

File: src/lib/game/world/content-queue.js (hunk 2 above)
Comment (fallenoak) [inline src/lib/game/world/content-queue.js]: Oh, good catch! I'm still learning what all ```Map``` and ```Set``` can do, I guess. :D

File: src/lib/game/world/content-queue.js (hunk 3 above)
Comment (timkurvers) [inline src/lib/game/world/content-queue.js]: Ah, I see! :+1: If not, it would probably be good to remove it for now (as well as the TODO a bit above it). Great idea to add at some point though. I feel it could be an extension to Map maybe, then we could have the queue itself handle the matching in `has` and `remove` for example.

Comment (timkurvers) [inline src/lib/game/world/content-queue.js]: On second thought, I'm not sure if extending Map is supported ._.

File: src/lib/pipeline/wmo/group/index.js [hunk 5]
```diff
@@ -58,7 +55,7 @@ class WMOGroup extends THREE.Mesh {
       });
     } else if (this.indoor) {
       // Default indoor vertex color: rgba(0.5, 0.5, 0.5, 1.0)
-      data.MOVT.vertices.forEach(function(vertex, index) {
+      data.MOVT.vertices.forEach(function(_vertex, index) {
```
Comment (timkurvers) [inline src/lib/pipeline/wmo/group/index.js]: Ah, good catch! :+1:

File: src/lib/game/world/content-queue.js (hunk 1 above)
Comment (fallenoak) [inline src/lib/game/world/content-queue.js]: The idea is to yield back to anything else that's been waiting while the queue items were being processed (ie cooperative multitasking). I suppose the value could even be ```0```, and not configured. ```0``` seemed like it might be relying a bit heavily on convention in JS VMs to always yield on ```setTimeout```, though.

File: src/lib/game/world/content-queue.js (hunk 3 above)
Comment (fallenoak) [inline src/lib/game/world/content-queue.js]: Not sure-- let's just remove it for now. :+1:

**Comment by fallenoak** [comment]
Hopefully the new WMOManager is a lot more readable than the old one, and has less repeated code.

**Comment by fallenoak** [comment]
Fixed up a few things!

File: src/lib/game/world/content-queue.js [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+
+    this.schedule = ::this.schedule;
+    this.run = ::this.run;
+
+    this.schedule();
+  }
+
+  has(keyPattern) {
+    // todo: allow wildcards (ie 8-*)
+    return this.queue.has(keyPattern);
```
Comment (timkurvers) [inline src/lib/game/world/content-queue.js]: Sorry, forgot to comment on this use of `keyPattern` earlier.

Comment (fallenoak) [inline src/lib/game/world/content-queue.js]: Woops, yeah, let me nuke this one, too.

**Comment by timkurvers** [comment]
Gave it a spin, good stuff! :tada:
